# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  release:
   # needs: container
    name: Process deployment manifest
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ Checkout manifest"
        uses: actions/checkout@v3
        with:
          ref: master
          repository: https://github.com/chenzhenghan83/argocdgithub
          token: ${{ secrets.CDACCESSTOKEN }}
          path: ./app

      - name: "âœ Write tag info of current build"
        run: |
          valuesFile=./app/deployment.yaml
          oldTag=$(cat deployment.yaml | grep tag: | head -n 1 | awk '{print $2}' | tr -d '\n')
          echo "** $valuesFile ::: replacing $oldTag with ${{ needs.container.outputs.mytag }}"
          sed -i "s|$oldTag|${{ needs.container.outputs.mytag }}|" $valuesFile
      - name: "ğŸ–ƒ Commit changes of current build"
        run: |
          cd ./app
          git config user.email "chen.zhenghan@stengg.com"
          git config user.name "chenzhenghan83"
          git commit -m "[auto] version updated" -a
      - name: "ğŸš€ Upload manifest"
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: ./
          branch: master
          repository: https://github.com/chenzhenghan83/argocdgithub
          github_token: ${{ secrets.PAT }}
